### PR TITLE
Bugfixes

### LINKED ISSUE #55: Clicking on AWQ in quest log misaligns it
AWQ 0.43
WoW 11.0.2

Clicking on the title of the world quest misaligns it in the frames... I'm going to test it some more but here's what it looking like: 

image

### LINKED ISSUE #56: Wrong display of pet battle rewards
Hi,

with v0.43.0, when tracking pet battle WQs there seems to be an issue with the display of the rewards, for instance:

- bandages: WQs with as, e.g., 15 or 18 as reward only show as 10 for each in the quest log
- charms: WQs with >10 charms only appear as 1
- training stone: all rewards appear as 1

2024-08-22-211442_498x267_scrot

### PR DESCRIPTION
**Pull request by Shauren**
Closes #55
Closes #56

### CODE REVIEW

File: QuestFrame.lua [hunk 1]
```diff
@@ -594,8 +594,8 @@ local function TitleButton_Initiliaze(button)
 		button.TagText:SetWidth(28)
 		button.TagText:Hide()
 
-		button.Text:ClearAllPoints()
-		button.Text:SetPoint("TOPRIGHT", button.TagText, "TOPLEFT", -4, 0)
+		button.Text:ClearPoint("RIGHT")
```
Comment (Shauren) [inline QuestFrame.lua:597]: this leaves the default TOP anchor alone and only customizes RIGHT one

**Comment by GurliGebis** [comment]
Thanks - I'll take a look at it tomorrow (It's over midnight here) 🙂
